--local using = assert((_G or getfenv(0) or {}).pvl_namespacer_get) -- @formatter:off
--
--local Scopify = using "System.Scopify"
--local EScopes = using "System.EScopes"
--
--local U = using "[built-in]" [[ VWoWUnit ]] -- @formatter:on         
--
--Scopify(EScopes.Function, {})
--
--local TG = U.TestsEngine:CreateOrUpdateGroup { Name = "System.Core.Tests.InheritanceTestbed" }
--
--Scopify(EScopes.Function, {})
--
--TG:AddFact("Inheritance.NamespaceBlending.GivenEmptyMixinsTableToBlend.ShouldThrow",
--        function()
--            -- ARRANGE
--
--            -- ACT
--            function action()
--                using "[declare]" "Foo.Bar.Ping" "[blend]" {}
--            end
--
--            -- ASSERT
--            U.Should.Throw(action)
--        end
--)
